spring:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: env.properties

  datasource:
    url: jdbc:mysql://localhost:3306/birds
    username: DB_USER
    password: DB_PASSWORD
    driverClassName: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
