spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/birds
    username: 
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
