spring:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/birds
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
